package Cliente.calculadoraApp;


/**
* calculadoraApp/calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 2 de abril de 2024 12:40:53 PM CST
*/

public interface calculadora extends calculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface calculadora
