package Servidor.calculadoraApp;

/**
* calculadoraApp/calculadoraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculadora.idl
* martes 2 de abril de 2024 12:40:53 PM CST
*/

public final class calculadoraHolder implements org.omg.CORBA.portable.Streamable
{
  public calculadora value = null;

  public calculadoraHolder ()
  {
  }

  public calculadoraHolder (calculadora initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculadoraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculadoraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculadoraHelper.type ();
  }

}
